// ═══════════════════════════════════════════════
//  MUSSOORIE TRIP DATA
//  Edit this file to update any trip info
// ═══════════════════════════════════════════════

const TRIP_START = new Date('2026-04-25T17:00:00+05:30');

// ── ITINERARY ─────────────────────────────────
const itinerary = [
  {
    day: 1,
    date: 'Saturday, April 25',
    title: 'Arrival & Mall Road Vibes',
    emoji: '🚗',
    color: '#c9a84c',
    events: [
      {
        time: '5:00 PM',
        endTime: '6:30 PM',
        duration: '~1.5 hrs',
        title: 'Arrive in Dehradun → Cab to Mussoorie',
        desc: 'Land in Dehradun and grab a cab up the winding mountain road. Sit back, roll the windows down, and feel the temperature drop.',
        icon: '🚕',
        type: 'travel',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=Mussoorie+Uttarakhand',
      },
      {
        time: '7:00 PM',
        endTime: '7:30 PM',
        duration: '30 min',
        title: 'Check In – Shalom Backpackers',
        desc: 'Drop your bags, claim your bed, freshen up. Home for the first two nights.',
        icon: '🎒',
        type: 'stay',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Shalom+Backpackers+Mussoorie',
      },
      {
        time: '7:30 PM',
        endTime: '10:30 PM',
        duration: '3 hrs',
        title: 'Mall Road – Explore, Eat & Vibe',
        desc: 'Head straight to Mall Road. No agenda, just vibes — street food, shopping, music, and finally catching up with the squad.',
        icon: '🌃',
        type: 'explore',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Mall+Road+Mussoorie',
      },
    ],
  },
  {
    day: 2,
    date: 'Sunday, April 26',
    title: 'The Explorer Day',
    emoji: '🥾',
    color: '#5a9e6f',
    events: [
      {
        time: '8:00 AM',
        endTime: '8:30 AM',
        duration: '30 min',
        title: 'Breakfast Near Hostel',
        desc: 'Quick breakfast before hitting the road. Try Lovely Omelette Centre for a budget local bite.',
        icon: '🍳',
        type: 'food',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Lovely+Omelette+Centre+Mussoorie',
      },
      {
        time: '9:00 AM',
        endTime: '10:30 AM',
        duration: '1.5 hrs',
        title: 'Dalai Hills',
        desc: 'Tibetan temple complex with panoramic Doon Valley views. Peaceful, photogenic, and the perfect way to start the day.',
        icon: '⛩️',
        type: 'explore',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=Dalai+Hills+Mussoorie',
      },
      {
        time: '11:00 AM',
        endTime: '1:30 PM',
        duration: '2.5 hrs',
        title: 'George Everest Peak',
        desc: 'Trek to the historic ruins of Sir George Everest\'s home on a dramatic ridge. Views of two valleys simultaneously. The last 15 mins are steep.',
        icon: '🏔️',
        type: 'trek',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=George+Everest+Peak+Mussoorie',
      },
      {
        time: '1:30 PM',
        endTime: '2:15 PM',
        duration: '45 min',
        title: 'Lunch – Camel\'s Back Road Dhabas',
        desc: 'Stop at a roadside dhaba for dal, roti, and chai. Keep it simple and local.',
        icon: '🍛',
        type: 'food',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Camels+Back+Road+Mussoorie',
      },
      {
        time: '2:30 PM',
        endTime: '4:00 PM',
        duration: '1.5 hrs',
        title: "Cloud's End",
        desc: 'The western edge of Mussoorie where roads fade into dense forest. Oak, rhododendron, and misty silence.',
        icon: '☁️',
        type: 'explore',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=Clouds+End+Mussoorie',
      },
      {
        time: '4:30 PM',
        endTime: '6:00 PM',
        duration: '1.5 hrs',
        title: 'Corn Village',
        desc: 'Fresh corn roasted on coal with lemon and masala. Classic Mussoorie experience. Stock up on snacks too.',
        icon: '🌽',
        type: 'food',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=Corn+Village+Mussoorie',
      },
      {
        time: '7:30 PM',
        endTime: '9:30 PM',
        duration: '2 hrs',
        title: 'Dinner at Kalsang Restaurant',
        desc: 'End the day with Tibetan momos, thukpa, and the best steamed dumplings in Mussoorie. Always busy, so arrive a little early.',
        icon: '🥟',
        type: 'food',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=Kalsang+Restaurant+Mussoorie',
      },
    ],
  },
  {
    day: 3,
    date: 'Monday, April 27',
    title: 'Property Upgrade & Landour Charm',
    emoji: '🏡',
    color: '#c4622d',
    events: [
      {
        time: '9:00 AM',
        endTime: '10:00 AM',
        duration: '1 hr',
        title: 'Final Breakfast at Hostel + Checkout',
        desc: 'Pack up, check out from Shalom, and say goodbye to the hostel life.',
        icon: '🎒',
        type: 'stay',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Shalom+Backpackers+Mussoorie',
      },
      {
        time: '10:30 AM',
        endTime: '11:30 AM',
        duration: '1 hr',
        title: 'Check Into Private BnB 🏡',
        desc: 'Move into the new private property. Claim rooms, settle in, take a moment to appreciate the upgrade.',
        icon: '🏡',
        type: 'stay',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=BnB+Mussoorie',
      },
      {
        time: '12:30 PM',
        endTime: '2:00 PM',
        duration: '1.5 hrs',
        title: 'Head Up to Landour + Char Dukan',
        desc: 'THE Landour stop. Sit outside Bandookwala\'s, order honey pancakes, Maggi, and hot chai. Take your time here — this is the soul of the trip.',
        icon: '🥞',
        type: 'food',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=Char+Dukan+Landour+Mussoorie',
      },
      {
        time: '2:00 PM',
        endTime: '4:00 PM',
        duration: '2 hrs',
        title: 'Wander Landour & Sister\'s Bazaar',
        desc: 'Explore the quiet colonial lanes of Landour. Browse Sister\'s Bazaar, spot old cottages, maybe stumble upon Ruskin Bond\'s house.',
        icon: '🚶',
        type: 'explore',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=Sisters+Bazaar+Landour+Mussoorie',
      },
      {
        time: '4:30 PM',
        endTime: '5:30 PM',
        duration: '1 hr',
        title: 'Coffee at Landour Bakehouse',
        desc: 'Post-wander pit stop. Fresh sourdough, cinnamon rolls, and filter coffee in a charming rustic bakery.',
        icon: '☕',
        type: 'food',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=Landour+Bakehouse+Mussoorie',
      },
      {
        time: '5:30 PM',
        endTime: '7:00 PM',
        duration: '1.5 hrs',
        title: 'Lal Tibba – Sunset Views',
        desc: 'Highest point in Mussoorie at 2275m. Catch the sunset and — if clear — spot Himalayan peaks through the telescope. Pay the small telescope fee, it\'s worth it.',
        icon: '🌅',
        type: 'explore',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=Lal+Tibba+Mussoorie',
      },
      {
        time: '8:00 PM',
        endTime: '9:30 PM',
        duration: 'Optional',
        title: 'Dhanaulti (Optional)',
        desc: 'If the group is up for more adventure, head 25km to Dhanaulti for a nighttime cedars-and-silence experience.',
        icon: '🌲',
        type: 'optional',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=Dhanaulti+Uttarakhand',
      },
    ],
  },
  {
    day: 4,
    date: 'Tuesday, April 28',
    title: 'Choose Your Own Adventure',
    emoji: '🎲',
    color: '#7b6fcc',
    events: [
      {
        time: 'All Day',
        endTime: '',
        duration: 'Full day',
        title: 'Option A: Explorer Mode',
        desc: 'Go knock out Dhanaulti, revisit Corn Village, or hit any spots you missed. The BnB driver can take you around.',
        icon: '🗺️',
        type: 'explore',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=Dhanaulti+Uttarakhand',
      },
      {
        time: 'All Day',
        endTime: '',
        duration: 'Full day',
        title: 'Option B: Chill & Unplug',
        desc: 'Morning trek from the BnB, then games, great food, and doing absolutely nothing at all. Mountains as the backdrop. This might actually be the best day.',
        icon: '😌',
        type: 'chill',
        mapsLink: '',
      },
    ],
  },
  {
    day: 5,
    date: 'Wednesday, April 29',
    title: 'Heading Home',
    emoji: '👋',
    color: '#8fa89e',
    events: [
      {
        time: '8:00 AM',
        endTime: '9:30 AM',
        duration: '1.5 hrs',
        title: 'Final Breakfast at BnB',
        desc: 'Savour the last mountain breakfast. Take it slow. Take lots of photos.',
        icon: '☀️',
        type: 'food',
        mapsLink: '',
      },
      {
        time: '10:00 AM',
        endTime: '11:00 AM',
        duration: '1 hr',
        title: 'Pack Up & Check Out',
        desc: 'Leave the place clean, collect your stuff, say your goodbyes to the mountains.',
        icon: '📦',
        type: 'stay',
        mapsLink: '',
      },
      {
        time: '11:00 AM',
        endTime: '9:00 PM',
        duration: 'Full day',
        title: 'Travel Back Home',
        desc: 'Cab down to Dehradun, then home via train/bus. Window seat mandatory. Playlist curated.',
        icon: '🚗',
        type: 'travel',
        mapsLink: 'https://www.google.com/maps/dir/?api=1&destination=Dehradun+Railway+Station',
      },
    ],
  },
];

// ── PLACES TO SEE ─────────────────────────────
const places = [
  {
    name: 'Mall Road',
    day: '1',
    dayLabel: 'Day 1',
    category: 'Experience',
    duration: '2–3 hrs',
    bestTime: 'Evening 6–10 PM',
    difficulty: 'Easy',
    entryFee: 'Free',
    description: 'The beating heart of Mussoorie. Lined with shops, cafes, street food stalls, and live music. Best after dark when the fairy lights come on.',
    tips: 'Keep valuables close in crowds. Bargain at souvenir shops. Try the local peanut chikki.',
    image: 'https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=800&q=80',
    fallbackGradient: 'linear-gradient(135deg, #2d4a3e, #c9a84c)',
    mapsLink: 'https://www.google.com/maps/search/?api=1&query=Mall+Road+Mussoorie',
    dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Mall+Road+Mussoorie',
  },
  {
    name: 'Dalai Hills',
    day: '2',
    dayLabel: 'Day 2',
    category: 'Viewpoint + Temple',
    duration: '1–2 hrs',
    bestTime: 'Morning 8–11 AM',
    difficulty: 'Easy',
    entryFee: 'Free',
    description: 'A serene Tibetan monastery complex atop a ridge. Panoramic views of the Doon Valley with prayer flags fluttering in the mountain breeze.',
    tips: 'Dress respectfully inside the temple. Sunrise views are spectacular. Go on a clear day.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    fallbackGradient: 'linear-gradient(135deg, #1a3a2e, #4a7a5e)',
    mapsLink: 'https://www.google.com/maps/search/?api=1&query=Dalai+Hills+Mussoorie',
    dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Dalai+Hills+Mussoorie',
  },
  {
    name: 'George Everest Peak',
    day: '2',
    dayLabel: 'Day 2',
    category: 'Trek + Heritage',
    duration: '2–3 hrs',
    bestTime: 'Morning 9 AM–12 PM',
    difficulty: 'Moderate',
    entryFee: '₹25',
    description: 'Historic ruins of Sir George Everest\'s home on a dramatic ridge. Valley views on BOTH sides simultaneously. The last 15 minutes are steep.',
    tips: 'Wear proper closed-toe shoes. Carry water. Go on a clear day for Himalayan views.',
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=800&q=80',
    fallbackGradient: 'linear-gradient(135deg, #2c4a3e, #5a8a74)',
    mapsLink: 'https://www.google.com/maps/search/?api=1&query=George+Everest+Peak+Mussoorie',
    dirLink: 'https://www.google.com/maps/dir/?api=1&destination=George+Everest+Peak+Mussoorie',
  },
  {
    name: "Cloud's End",
    day: '2',
    dayLabel: 'Day 2',
    category: 'Nature',
    duration: '1–2 hrs',
    bestTime: 'Afternoon',
    difficulty: 'Easy',
    entryFee: '₹50',
    description: 'The western tip of Mussoorie where the road ends and dense forest begins. Oak, rhododendron, and a literal feeling of being at the edge of the world.',
    tips: 'Great for bird watching. Carry a jacket — it gets windy. Small entry fee at the gate.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    fallbackGradient: 'linear-gradient(135deg, #1a2c26, #3d6b5a)',
    mapsLink: 'https://www.google.com/maps/search/?api=1&query=Clouds+End+Mussoorie',
    dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Clouds+End+Mussoorie',
  },
  {
    name: 'Landour',
    day: '3',
    dayLabel: 'Day 3',
    category: 'Heritage + Charm',
    duration: 'Half Day',
    bestTime: 'Afternoon 12–5 PM',
    difficulty: 'Easy',
    entryFee: 'Free',
    description: 'Mussoorie\'s quieter, older sister. Colonial bungalows, artistic cafes, and Ruskin Bond\'s actual home. These lanes feel like a different era.',
    tips: 'Walk the Clocktower loop. Visit Char Dukan without fail. Carry cash — most shops are card-free.',
    image: 'https://images.unsplash.com/photo-1520208422-10dfa4e17352?auto=format&fit=crop&w=800&q=80',
    fallbackGradient: 'linear-gradient(135deg, #3a2a1a, #8a5a2a)',
    mapsLink: 'https://www.google.com/maps/search/?api=1&query=Landour+Mussoorie',
    dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Landour+Mussoorie',
  },
  {
    name: "Sister's Bazaar",
    day: '3',
    dayLabel: 'Day 3',
    category: 'Wander',
    duration: '1 hr',
    bestTime: 'Afternoon',
    difficulty: 'Easy',
    entryFee: 'Free',
    description: 'A small, slow market in the heart of Landour. Old churches, tiny shops, and the kind of quiet that makes you want to stay forever.',
    tips: 'Visit the old church nearby. Buy local honey and handmade goods here.',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
    fallbackGradient: 'linear-gradient(135deg, #2a1a3a, #6a4a8a)',
    mapsLink: 'https://www.google.com/maps/search/?api=1&query=Sisters+Bazaar+Landour+Mussoorie',
    dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Sisters+Bazaar+Landour+Mussoorie',
  },
  {
    name: 'Lal Tibba',
    day: '3',
    dayLabel: 'Day 3',
    category: 'Viewpoint',
    duration: '1–1.5 hrs',
    bestTime: 'Sunset 5–6:30 PM',
    difficulty: 'Easy',
    entryFee: 'Small fee for telescope',
    description: 'The highest point in Mussoorie at 2275m. On a clear day you can see Kedarnath and Badrinath through the telescope. Sunset here is something else.',
    tips: 'The ₹10 telescope fee is 100% worth it. Get there 30 min before sunset. Check if it\'s clear first.',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80',
    fallbackGradient: 'linear-gradient(135deg, #1a1a2c, #3a3a6a)',
    mapsLink: 'https://www.google.com/maps/search/?api=1&query=Lal+Tibba+Mussoorie',
    dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Lal+Tibba+Mussoorie',
  },
  {
    name: 'Dhanaulti',
    day: '3–4',
    dayLabel: 'Day 3/4',
    category: 'Day Trip',
    duration: '3–4 hrs',
    bestTime: 'Morning 9 AM–1 PM',
    difficulty: 'Easy',
    entryFee: '₹100 (Eco Park)',
    description: '25km from Mussoorie — dense cedar forests, a peaceful eco park, and a dramatic 180° Himalayan backdrop. Far fewer tourists than Mussoorie.',
    tips: 'Carry an extra layer — it\'s colder here. Takes ~45 min by cab. Best visited as a morning trip.',
    image: 'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?auto=format&fit=crop&w=800&q=80',
    fallbackGradient: 'linear-gradient(135deg, #1a2c1a, #4a7a4a)',
    mapsLink: 'https://www.google.com/maps/search/?api=1&query=Dhanaulti+Uttarakhand',
    dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Dhanaulti+Uttarakhand',
  },
];

// ── FOOD GUIDE ────────────────────────────────
const foodGuide = [
  {
    area: 'all',
    areaLabel: '⭐ All',
  },
  {
    area: 'mall-road',
    areaLabel: '🌃 Mall Road',
    places: [
      {
        name: 'Kalsang Restaurant',
        emoji: '🥟',
        cuisine: 'Tibetan / Chinese',
        specialty: 'Steamed Momos & Thukpa',
        price: '₹₹',
        priceNum: 2,
        timings: '11:00 AM – 10:00 PM',
        bestFor: 'Dinner on Day 1',
        rating: 4.5,
        localRec: true,
        notes: 'The most famous restaurant on Mall Road. Get the steamed momos, thukpa, and tingmo. Always crowded — arrive a little early.',
        image: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?auto=format&fit=crop&w=600&q=80',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Kalsang+Restaurant+Mall+Road+Mussoorie',
        dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Kalsang+Restaurant+Mussoorie',
      },
      {
        name: 'Lovely Omelette Centre',
        emoji: '🍳',
        cuisine: 'Street Food',
        specialty: 'Loaded Omelettes',
        price: '₹',
        priceNum: 1,
        timings: '7:00 AM – 11:00 PM',
        bestFor: 'Breakfast or late-night snack',
        rating: 4.3,
        localRec: true,
        notes: 'Super cheap, super good. The stuffed masala omelette is a must. Open very late — perfect post-Mall Road walk snack.',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Lovely+Omelette+Centre+Mussoorie',
        dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Lovely+Omelette+Centre+Mussoorie',
      },
      {
        name: 'Cafe Ivy',
        emoji: '☕',
        cuisine: 'Cafe / Continental',
        specialty: 'Coffee & Mountain Views',
        price: '₹₹₹',
        priceNum: 3,
        timings: '9:00 AM – 9:00 PM',
        bestFor: 'Morning coffee or evening sit-down',
        rating: 4.4,
        localRec: false,
        notes: 'Great outdoor seating with a view. A little pricey for the mountains, but worth it for at least one sit-down meal. Nice for the group.',
        image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=600&q=80',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Cafe+Ivy+Mussoorie',
        dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Cafe+Ivy+Mussoorie',
      },
      {
        name: 'Prakash Store',
        emoji: '🍪',
        cuisine: 'Snacks / Local',
        specialty: 'Kachodis, Namkeen & Local Chips',
        price: '₹',
        priceNum: 1,
        timings: '9:00 AM – 8:00 PM',
        bestFor: 'Stock up before trek days',
        rating: 4.2,
        localRec: true,
        notes: 'Local institution for 60+ years. Buy their kachodis and namkeen for trek snacks. Very affordable and genuinely local.',
        image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Prakash+Store+Mussoorie',
        dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Prakash+Store+Mussoorie',
      },
      {
        name: 'Green Restaurant',
        emoji: '🥗',
        cuisine: 'Multi-Cuisine / Indian',
        specialty: 'Pahadi Thali',
        price: '₹₹',
        priceNum: 2,
        timings: '12:00 PM – 10:00 PM',
        bestFor: 'Lunch or dinner fallback',
        rating: 4.0,
        localRec: false,
        notes: 'Decent food, reliable, always open. Try the pahadi thali for a local taste. Good for large groups.',
        image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=600&q=80',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Green+Restaurant+Mussoorie',
        dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Green+Restaurant+Mussoorie',
      },
    ],
  },
  {
    area: 'landour',
    areaLabel: '🏡 Landour',
    places: [
      {
        name: 'Char Dukan (Bandookwala\'s)',
        emoji: '🥞',
        cuisine: 'Cafe / Snacks',
        specialty: 'Honey Pancakes & Maggi',
        price: '₹₹',
        priceNum: 2,
        timings: '8:00 AM – 6:00 PM',
        bestFor: 'Day 3 — non-negotiable',
        rating: 4.8,
        localRec: true,
        notes: 'THE iconic Landour stop for decades. Sit outside on wooden benches, order pancakes with honey & butter, Maggi, and chai. Absolute bliss.',
        image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=600&q=80',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Char+Dukan+Landour+Mussoorie',
        dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Char+Dukan+Landour+Mussoorie',
      },
      {
        name: 'Landour Bakehouse',
        emoji: '🥐',
        cuisine: 'Artisan Bakery / Cafe',
        specialty: 'Sourdough, Cinnamon Rolls & Filter Coffee',
        price: '₹₹',
        priceNum: 2,
        timings: '8:00 AM – 6:00 PM',
        bestFor: 'Mid-Landour coffee break',
        rating: 4.6,
        localRec: true,
        notes: 'Run by a wonderful couple. Fresh bread, incredible pastries, and really good filter coffee. Very limited seating so arrive early.',
        image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Landour+Bakehouse+Mussoorie',
        dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Landour+Bakehouse+Mussoorie',
      },
      {
        name: "Anil's Cafe",
        emoji: '🍵',
        cuisine: 'Local / Indian',
        specialty: 'Parathas & Chai',
        price: '₹',
        priceNum: 1,
        timings: '7:00 AM – 2:00 PM',
        bestFor: 'Budget morning breakfast',
        rating: 4.1,
        localRec: true,
        notes: 'No frills, all flavour. Parathas, omelettes, and the creamiest chai. The most local experience you\'ll have in Landour.',
        image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=600&q=80',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Anil+Cafe+Landour+Mussoorie',
        dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Anil+Cafe+Landour+Mussoorie',
      },
    ],
  },
  {
    area: 'on-the-way',
    areaLabel: '🛣️ On The Way',
    places: [
      {
        name: "Camel's Back Road Dhabas",
        emoji: '🍛',
        cuisine: 'Dhaba',
        specialty: 'Dal, Roti & Chai',
        price: '₹',
        priceNum: 1,
        timings: '8:00 AM – 6:00 PM',
        bestFor: 'Quick lunch on trek days',
        rating: 4.0,
        localRec: true,
        notes: 'Small roadside dhabas along the scenic Camel\'s Back Road. Unpretentious, filling, and incredibly cheap. Fuel before or after George Everest.',
        image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=600&q=80',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Camels+Back+Road+Mussoorie',
        dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Camels+Back+Road+Mussoorie',
      },
      {
        name: 'Corn Village Stalls',
        emoji: '🌽',
        cuisine: 'Street Food',
        specialty: 'Coal-Roasted & Masala Corn',
        price: '₹',
        priceNum: 1,
        timings: '10:00 AM – 7:00 PM',
        bestFor: 'Day 2 afternoon snack',
        rating: 4.3,
        localRec: true,
        notes: 'Fresh corn roasted over coal, rubbed with lemon, butter, and spicy masala. Get both the roasted and boiled versions. A quintessential hill-station experience.',
        image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Corn+Village+Mussoorie',
        dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Corn+Village+Mussoorie',
      },
    ],
  },
  {
    area: 'dhanaulti',
    areaLabel: '🌲 Dhanaulti',
    places: [
      {
        name: 'Eco Park Dhabas',
        emoji: '🌿',
        cuisine: 'Pahadi / North Indian',
        specialty: 'Aloo ke Gutke & Rajma Chawal',
        price: '₹',
        priceNum: 1,
        timings: '8:00 AM – 7:00 PM',
        bestFor: 'Lunch during Dhanaulti visit',
        rating: 4.1,
        localRec: true,
        notes: 'Simple roadside eateries near the Eco Park. Try aloo ke gutke (local spiced potatoes) and rajma chawal. Very hearty pahadi comfort food.',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Dhanaulti+Eco+Park+restaurant+Uttarakhand',
        dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Dhanaulti+Eco+Park+Uttarakhand',
      },
      {
        name: 'Snow Valley Cafe',
        emoji: '❄️',
        cuisine: 'Cafe / Multi-Cuisine',
        specialty: 'Hot Soups & Mountain Snacks',
        price: '₹₹',
        priceNum: 2,
        timings: '9:00 AM – 7:00 PM',
        bestFor: 'Warm up after the forest walk',
        rating: 3.9,
        localRec: false,
        notes: 'A warmup stop near the cedar forest. The hot tomato soup and garlic toast are perfect on a cold Dhanaulti afternoon.',
        image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=600&q=80',
        mapsLink: 'https://www.google.com/maps/search/?api=1&query=Snow+Valley+Resort+Dhanaulti',
        dirLink: 'https://www.google.com/maps/dir/?api=1&destination=Dhanaulti+Uttarakhand',
      },
    ],
  },
];

// ── PACKING LIST ──────────────────────────────
const packingList = [
  {
    category: '👕 Clothing',
    items: [
      'Warm fleece or hoodie (nights are cold, even in April)',
      'Light rain jacket / windcheater',
      'Comfortable walking shoes / sneakers',
      'Socks x4 (always underestimated)',
      'T-shirts x3–4',
      'One pair jeans or track pants',
      'Sleepwear',
    ],
  },
  {
    category: '🎒 Essentials',
    items: [
      'Power bank (you\'ll need it constantly)',
      'Portable charger cable',
      'Earphones / headphones',
      'Sunscreen SPF 50+',
      'Sunglasses',
      'Cap or beanie',
      'Small day backpack for treks',
    ],
  },
  {
    category: '💊 Health & Hygiene',
    items: [
      'Basic first aid kit (plasters, antiseptic)',
      'Motion sickness pills (mountain roads!)',
      'Paracetamol / Dolo',
      'Lip balm — mountain air is dry',
      'Moisturiser',
      'Hand sanitizer',
      'Altitude tablets (optional — 2200m is fine for most)',
    ],
  },
  {
    category: '📸 Tech',
    items: [
      'Camera (or just use your phone — the camera is great)',
      'Extra memory card',
      'Universal adapter',
      'Headlamp or torch',
    ],
  },
  {
    category: '💵 Money',
    items: [
      'Cash (₹3000+ recommended — many spots don\'t take UPI)',
      'UPI set up and working',
      'Debit / Credit card as backup',
    ],
  },
];

// ── WEATHER ───────────────────────────────────
const weather = {
  month: 'April',
  day: { min: 16, max: 22, icon: '⛅' },
  night: { min: 8, max: 12, icon: '🌙' },
  condition: 'Partly Cloudy, occasional mist',
  tip: 'Light layers work well. Evenings & nights can be genuinely cold. Always carry a jacket.',
};
